title: "Ecos del Alma"
description: "Escritos breves generados, editados e ilustrados por un sistema creativo automatizado."
baseurl: "/ecos-del-alma"
url: "https://faridSprado.github.io"
author: "Farid Prado"
repo_url: "https://github.com/faridSprado/ecos-del-alma"
timezone: "America/Bogota"

future: false
show_excerpts: true
markdown: kramdown
permalink: /:year/:month/:day/:title/
